### ISSUE TITLE
Can't install nvidia driver unless disable nouveau

### ISSUE THREAD

**Issue by kkc** [wbuchwalter/blog-posts#2]
as title, before I generate the template for deployment, I need to modify `acs-engine/parts/kubernetesagentcustomdata.yml` and add following line to disable nouveau.

```
- sudo rmmod nouveau
- sudo sh -c "echo \"blacklist nouveau\" >> /etc/modprobe.d/blacklist.conf"
- sudo update-initramfs -u
- curl -L -sf https://raw.githubusercontent.com/ritazh/acs-k8s-gpu/master/install-nvidia-driver.sh | sudo sh
```

I was wondering how can you able to install nvidia driver without removing nouveau.
Thx a lot

**Comment by wbuchwalter** [comment]
Seems like the base ubuntu image changed since I wrote my article.  
When doing what you suggested, the node will eventually report a GPU, but it's taking much longer than expected. Your solution seems to be more efficient.

**Comment by wbuchwalter** [comment]
I updated the code with your corrections: https://github.com/wbuchwalter/acs-engine/blob/k8s-gpu/parts/kubernetesagentcustomdata.yml

Thanks!

**Comment by wbuchwalter** [comment]
Actually my issue was caused by something else entirely.
It was caused by a kernel upgrade happening after the driver installation. This is a new change that occurred in acs-engine a few days ago.
By disabling the kernel upgrade, or doing the driver installation after the upgrade, the GPU shows up correctly, even without your changes.

**Comment by wbuchwalter** [comment]
Last Update (hopefully :smile: ):
When Using `NC` series VM (K80 GPU), no need to remove the nouveau drivers.
But when using the `NV` series VM (M60 GPU) it is indeed needed to do as you described otherwise the GPU won't show up.  

All my clusters are using `NC` series that's why I wasn't seeing your issue.

Thanks!
